version: '3'

services:
  app:
    container_name: genny
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/genny
    # networks:
    #   - nginx-proxy-manager_default

  db:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    # networks:
    #   - nginx-proxy-manager_default

  jaeger:
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    image: jaegertracing/all-in-one:1.43
    depends_on:
      - app
    # networks:
    #   - nginx-proxy-manager_default

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./utils/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app