version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5173:5173"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/genny

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
