name: Build and test

on:
    push:
        branches:
        - main
    pull_request:

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint frontend
        run: npm run fe:lint
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint frontend
        run: npm run api:lint
  yaml-lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lint yaml
        uses: ibiqlik/action-yamllint@v3
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run fe:build
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build api
        run: npm run api:build